# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/borek/Desktop/mimhex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/borek/Desktop/mimhex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/borek/Desktop/mimhex/CMakeFiles /home/borek/Desktop/mimhex/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/borek/Desktop/mimhex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) -f main/CMakeFiles/hex.dir/build.make main/CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named hex_benchmark

# Build rule for target.
hex_benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex_benchmark
.PHONY : hex_benchmark

# fast build rule for target.
hex_benchmark/fast:
	$(MAKE) -f main/CMakeFiles/hex_benchmark.dir/build.make main/CMakeFiles/hex_benchmark.dir/build
.PHONY : hex_benchmark/fast

#=============================================================================
# Target rules for targets named gather_patterns

# Build rule for target.
gather_patterns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gather_patterns
.PHONY : gather_patterns

# fast build rule for target.
gather_patterns/fast:
	$(MAKE) -f patterns/gathering/CMakeFiles/gather_patterns.dir/build.make patterns/gathering/CMakeFiles/gather_patterns.dir/build
.PHONY : gather_patterns/fast

#=============================================================================
# Target rules for targets named hash_gen

# Build rule for target.
hash_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash_gen
.PHONY : hash_gen

# fast build rule for target.
hash_gen/fast:
	$(MAKE) -f patterns/utils/CMakeFiles/hash_gen.dir/build.make patterns/utils/CMakeFiles/hash_gen.dir/build
.PHONY : hash_gen/fast

#=============================================================================
# Target rules for targets named simple_pattern_conv

# Build rule for target.
simple_pattern_conv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_pattern_conv
.PHONY : simple_pattern_conv

# fast build rule for target.
simple_pattern_conv/fast:
	$(MAKE) -f patterns/utils/CMakeFiles/simple_pattern_conv.dir/build.make patterns/utils/CMakeFiles/simple_pattern_conv.dir/build
.PHONY : simple_pattern_conv/fast

#=============================================================================
# Target rules for targets named simple_hash_test

# Build rule for target.
simple_hash_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_hash_test
.PHONY : simple_hash_test

# fast build rule for target.
simple_hash_test/fast:
	$(MAKE) -f tests/CMakeFiles/simple_hash_test.dir/build.make tests/CMakeFiles/simple_hash_test.dir/build
.PHONY : simple_hash_test/fast

#=============================================================================
# Target rules for targets named simple_pattern_test

# Build rule for target.
simple_pattern_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_pattern_test
.PHONY : simple_pattern_test

# fast build rule for target.
simple_pattern_test/fast:
	$(MAKE) -f tests/CMakeFiles/simple_pattern_test.dir/build.make tests/CMakeFiles/simple_pattern_test.dir/build
.PHONY : simple_pattern_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... hex"
	@echo "... hex_benchmark"
	@echo "... gather_patterns"
	@echo "... hash_gen"
	@echo "... simple_pattern_conv"
	@echo "... simple_hash_test"
	@echo "... simple_pattern_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

