#!/bin/bash


if [ -z $1 ] ; then
  echo "Error: No argument. "
  echo "Proper use: "
  echo "   ./check_gathering_output data_filename"
  exit 1
fi

echo $1;

lineNo=0;
errorsCount=0;
cat $1 | while read line; do
  let "lineNo += 1";
  
  usedPattern=`echo $line | cut -f1 -d" "`;
  count=0;
  for pattern in `echo $line`; do
	 if [ $usedPattern -eq $pattern ]; then
		let "count += 1";
	 fi
  done
 # echo "Line: $lineNo    Count: $count";
  if [ $count -le 1 ] ; then
	 echo "Line $lineNo contains only $count occurences of used pattern!";
	 let "errorsCount += 1";
  fi
done

echo "Errors Found: $errorsCount";
